### ISSUE TITLE
Cache courses

### ISSUE THREAD

**Issue by gschorkopf** [gschorkopf/frolfr#110]
When I visit the courses page, it does not cache the request / store it in the ember store. It makes a request erry time

**Comment by gschorkopf** [comment]
Same with 'friends'!

**Comment by killpack** [comment]
Apparently that's normal behavior when you call `store.find('coolModel')` in Ember Data. So we're gonna have to be sneaky about using `store.all('coolModel')` (which never makes a request and only uses the cache) when appropriate.

**Comment by gschorkopf** [comment]
Interesting. I find it also interesting that the rounds route caches (which is great, since it's the most info). Think it's because we are fetching stuff this way?

```javascript
return this.store.find('user', 'current').then(function(model) {
    return model.get('scorecards');
});

**Comment by killpack** [comment]
Absolutely. Single record find calls are cached, and then the association is cached, too.

**Comment by gschorkopf** [comment]
Closing this for now, lower priority
