### ISSUE TITLE
Disable zoom on tapping on input field

### ISSUE THREAD

**Issue by gschorkopf** [gschorkopf/frolfr#129]
On mobile, when you tap on an input field, the screen zooms in on it. Looks really silly.

This is probably gonna be real hacky. Oh well.

**Comment by killpack** [comment]
Nah, shouldn't be hacky. From the Bootstrap docs:
> You can disable zooming capabilities on mobile devices by adding user-scalable=no to the viewport meta tag. This disables zooming, meaning users are only able to scroll, and results in your site feeling a bit more like a native application. Overall, we don't recommend this on every site, so use caution!

**Comment by gschorkopf** [comment]
:heart: :boot: strap

**Comment by gschorkopf** [comment]
Wow! Both of those emojis worked!
